name: Create Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build
        run: |
          npm install
          npm run build
          mv build demo-chrome-ext
          zip -r demo-chrome-ext-${{ github.ref_name }}.zip demo-chrome-ext

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: demo-chrome-ext-${{ github.ref_name }}.zip
          generate_release_notes: true
